workdir: /home/fabio/Desktop/assembly-miseq

threads: 4
mem_mb: 256000

# Adapter Removal parameters
adapterremoval:
    minquality: 20
    minlength: 31
    mm: 3
    minalignmentlength: 11
    optional: '--trimns --trimqualities --collapse'

# CD-HIT parameters
# program can be blastp, blastn, megablast or psiblast
# circle can be 1 or 0
cdhit:
    identity: 0.98
    program: 'blastn'
    circle: 1

# QUAST parameters
quast:
    reference: 'empty'
    genes: 'empty'

samples:
    'NG-19302_B208_lib327116_6377_1':
        forward: 'data/NG-19302_B208_lib327116_6377/NG-19302_B208_lib327116_6377_1_1.fastq.gz'
        reverse: 'data/NG-19302_B208_lib327116_6377/NG-19302_B208_lib327116_6377_1_2.fastq.gz'
